[package]
name = "openfairdb"
version = "0.8.21"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>", "slowtec GmbH <post@slowtec.de>"]
keywords = ["geo", "fair", "sustainability"]
homepage = "https://github.com/kartevonmorgen/openfairdb"
repository = "https://github.com/kartevonmorgen/openfairdb"
license = "AGPL-3.0-or-later"
edition = "2018"

[patch.crates-io]
ofdb-app = { path = "ofdb-app" }
ofdb-boundary = { path = "ofdb-boundary" }
ofdb-core = { path = "ofdb-core" }
ofdb-entities = { path = "ofdb-entities" }
ofdb-gateways = { path = "ofdb-gateways" }
geocoding = { git = "https://github.com/slowtec/geocoding", branch = "rustls" }

[workspace]
members = [
  ".",
  "ofdb-app",
  "ofdb-boundary",
  "ofdb-core",
  "ofdb-entities",
  "ofdb-gateways",
]

[dependencies]
anyhow = "*"
chrono = "*"
# clap 3 is supposed to introduce breaking changes
clap = "2"
csv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "*", features = ["sqlite"] }
dotenv = "*"
env_logger = "*"
# failure is only required for TantivyError
failure = "*"
fast_chemail = "*"
lazy_static = "*"
log = "*"
num-traits = "*"
maud = { version = "*", optional = true, features = ["rocket"] }
ofdb-app = { version = "*", optional = true }
ofdb-boundary = "*"
ofdb-core = "*"
ofdb-entities = "*"
ofdb-gateways = "*"
owning_ref = "*"
passwords = "*"
pwhash = "*"
regex = "*"
rocket = "*"
rocket_contrib = "*"
rocket_cors = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
strum = "*"
tantivy = "*"
thiserror = "1"
url = { version = "*", features = ["serde"] }
uuid = { version = "*", features = ["v4"] }

[dev-dependencies]
rand = "*"
ofdb-boundary = { version = "*", features = ["extra-derive"] }
ofdb-entities = { version = "*", features = ["builders"] }

[build-dependencies]
walkdir = "2"

[features]
default = ["email","frontend","app"]
email = []
frontend = ["maud"]
app = ["ofdb-app"]

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.ofdb-app]
opt-level = 'z'
